import { CedearInfo } from './types';

// Lista completa de CEDEARs operables en BYMA via Yahoo Finance (.BA suffix)
// Excluye: CEDEARs suspendidos (rusos), tickers B3 brasileros, y delisted
// Los ratios pueden variar — BYMA los ajusta periodicamente

export const CEDEAR_LIST: CedearInfo[] = [
  // ═══ TECNOLOGIA ═══
  { ticker: 'AAPL.BA', name: 'Apple Inc.', localTicker: 'AAPL', sector: 'Tecnologia', ratio: 20 },
  { ticker: 'MSFT.BA', name: 'Microsoft Corp.', localTicker: 'MSFT', sector: 'Tecnologia', ratio: 30 },
  { ticker: 'GOOGL.BA', name: 'Alphabet Inc.', localTicker: 'GOOGL', sector: 'Tecnologia', ratio: 58 },
  { ticker: 'META.BA', name: 'Meta Platforms', localTicker: 'META', sector: 'Tecnologia', ratio: 24 },
  { ticker: 'NVDA.BA', name: 'NVIDIA Corp.', localTicker: 'NVDA', sector: 'Semiconductores', ratio: 24 },
  { ticker: 'AMZN.BA', name: 'Amazon.com Inc.', localTicker: 'AMZN', sector: 'Tecnologia', ratio: 144 },
  { ticker: 'ADBE.BA', name: 'Adobe Inc.', localTicker: 'ADBE', sector: 'Tecnologia', ratio: 44 },
  { ticker: 'CRM.BA', name: 'Salesforce Inc.', localTicker: 'CRM', sector: 'Tecnologia', ratio: 18 },
  { ticker: 'ORCL.BA', name: 'Oracle Corp.', localTicker: 'ORCL', sector: 'Tecnologia', ratio: 3 },
  { ticker: 'INTC.BA', name: 'Intel Corp.', localTicker: 'INTC', sector: 'Semiconductores', ratio: 5 },
  { ticker: 'CSCO.BA', name: 'Cisco Systems', localTicker: 'CSCO', sector: 'Tecnologia', ratio: 5 },
  { ticker: 'IBM.BA', name: 'IBM Corp.', localTicker: 'IBM', sector: 'Tecnologia', ratio: 15 },
  { ticker: 'QCOM.BA', name: 'Qualcomm Inc.', localTicker: 'QCOM', sector: 'Semiconductores', ratio: 11 },
  { ticker: 'TXN.BA', name: 'Texas Instruments', localTicker: 'TXN', sector: 'Semiconductores', ratio: 5 },
  { ticker: 'AVGO.BA', name: 'Broadcom Inc.', localTicker: 'AVGO', sector: 'Semiconductores', ratio: 39 },
  { ticker: 'AMD.BA', name: 'AMD Inc.', localTicker: 'AMD', sector: 'Semiconductores', ratio: 10 },
  { ticker: 'AMAT.BA', name: 'Applied Materials', localTicker: 'AMAT', sector: 'Semiconductores', ratio: 5 },
  { ticker: 'LRCX.BA', name: 'Lam Research', localTicker: 'LRCX', sector: 'Semiconductores', ratio: 56 },
  { ticker: 'MU.BA', name: 'Micron Technology', localTicker: 'MU', sector: 'Semiconductores', ratio: 5 },
  { ticker: 'ADI.BA', name: 'Analog Devices', localTicker: 'ADI', sector: 'Semiconductores', ratio: 15 },
  { ticker: 'MRVL.BA', name: 'Marvell Technology', localTicker: 'MRVL', sector: 'Semiconductores', ratio: 14 },
  { ticker: 'TSM.BA', name: 'Taiwan Semiconductor', localTicker: 'TSM', sector: 'Semiconductores', ratio: 9 },
  { ticker: 'ASML.BA', name: 'ASML Holding', localTicker: 'ASML', sector: 'Semiconductores', ratio: 146 },
  { ticker: 'ARM.BA', name: 'ARM Holdings', localTicker: 'ARM', sector: 'Semiconductores', ratio: 27 },
  { ticker: 'SAP.BA', name: 'SAP SE', localTicker: 'SAP', sector: 'Tecnologia', ratio: 6 },
  { ticker: 'SHOP.BA', name: 'Shopify Inc.', localTicker: 'SHOP', sector: 'Tecnologia', ratio: 107 },
  { ticker: 'SNOW.BA', name: 'Snowflake Inc.', localTicker: 'SNOW', sector: 'Tecnologia', ratio: 30 },
  { ticker: 'PANW.BA', name: 'Palo Alto Networks', localTicker: 'PANW', sector: 'Tecnologia', ratio: 50 },
  { ticker: 'NOW.BA', name: 'ServiceNow Inc.', localTicker: 'NOW', sector: 'Tecnologia', ratio: 172 },
  { ticker: 'PLTR.BA', name: 'Palantir Technologies', localTicker: 'PLTR', sector: 'Tecnologia', ratio: 3 },
  { ticker: 'NFLX.BA', name: 'Netflix Inc.', localTicker: 'NFLX', sector: 'Entretenimiento', ratio: 48 },
  { ticker: 'SPOT.BA', name: 'Spotify Technology', localTicker: 'SPOT', sector: 'Entretenimiento', ratio: 28 },
  { ticker: 'DOCU.BA', name: 'DocuSign Inc.', localTicker: 'DOCU', sector: 'Tecnologia', ratio: 22 },
  { ticker: 'ROKU.BA', name: 'Roku Inc.', localTicker: 'ROKU', sector: 'Tecnologia', ratio: 13 },
  { ticker: 'PINS.BA', name: 'Pinterest Inc.', localTicker: 'PINS', sector: 'Tecnologia', ratio: 7 },
  { ticker: 'SNAP.BA', name: 'Snap Inc.', localTicker: 'SNAP', sector: 'Tecnologia', ratio: 1 },
  { ticker: 'RBLX.BA', name: 'Roblox Corp.', localTicker: 'RBLX', sector: 'Tecnologia', ratio: 2 },
  { ticker: 'ETSY.BA', name: 'Etsy Inc.', localTicker: 'ETSY', sector: 'E-Commerce', ratio: 16 },
  { ticker: 'EA.BA', name: 'Electronic Arts', localTicker: 'EA', sector: 'Entretenimiento', ratio: 14 },
  { ticker: 'EBAY.BA', name: 'eBay Inc.', localTicker: 'EBAY', sector: 'E-Commerce', ratio: 2 },
  { ticker: 'SONY.BA', name: 'Sony Group Corp.', localTicker: 'SONY', sector: 'Tecnologia', ratio: 8 },
  { ticker: 'ISRG.BA', name: 'Intuitive Surgical', localTicker: 'ISRG', sector: 'Tecnologia', ratio: 90 },
  { ticker: 'BABA.BA', name: 'Alibaba Group', localTicker: 'BABA', sector: 'E-Commerce', ratio: 9 },
  { ticker: 'JD.BA', name: 'JD.com Inc.', localTicker: 'JD', sector: 'E-Commerce', ratio: 4 },
  { ticker: 'SE.BA', name: 'Sea Ltd.', localTicker: 'SE', sector: 'E-Commerce', ratio: 32 },
  { ticker: 'BIDU.BA', name: 'Baidu Inc.', localTicker: 'BIDU', sector: 'Tecnologia', ratio: 11 },
  { ticker: 'NIO.BA', name: 'NIO Inc.', localTicker: 'NIO', sector: 'Automotriz', ratio: 4 },
  { ticker: 'TEAM.BA', name: 'Atlassian Corp.', localTicker: 'TEAM', sector: 'Tecnologia', ratio: 47 },
  { ticker: 'MSTR.BA', name: 'MicroStrategy', localTicker: 'MSTR', sector: 'Crypto', ratio: 20 },
  { ticker: 'SQ.BA', name: 'Block Inc.', localTicker: 'SQ', sector: 'Fintech', ratio: 20 },
  { ticker: 'PYPL.BA', name: 'PayPal Holdings', localTicker: 'PYPL', sector: 'Fintech', ratio: 8 },
  { ticker: 'GLOB.BA', name: 'Globant S.A.', localTicker: 'GLOB', sector: 'Tecnologia', ratio: 18 },
  { ticker: 'MELI.BA', name: 'MercadoLibre Inc.', localTicker: 'MELI', sector: 'E-Commerce', ratio: 120 },
  { ticker: 'ACN.BA', name: 'Accenture Plc', localTicker: 'ACN', sector: 'Tecnologia', ratio: 75 },
  { ticker: 'UBER.BA', name: 'Uber Technologies', localTicker: 'UBER', sector: 'Tecnologia', ratio: 2 },
  { ticker: 'ABNB.BA', name: 'Airbnb Inc.', localTicker: 'ABNB', sector: 'Tecnologia', ratio: 15 },
  { ticker: 'AI.BA', name: 'C3.AI Inc.', localTicker: 'AI', sector: 'Tecnologia', ratio: 5 },
  { ticker: 'UPST.BA', name: 'Upstart Holdings', localTicker: 'UPST', sector: 'Fintech', ratio: 5 },
  { ticker: 'HPQ.BA', name: 'HP Inc.', localTicker: 'HPQ', sector: 'Tecnologia', ratio: 1 },
  { ticker: 'INFY.BA', name: 'Infosys Ltd.', localTicker: 'INFY', sector: 'Tecnologia', ratio: 1 },
  { ticker: 'NTES.BA', name: 'NetEase Inc.', localTicker: 'NTES', sector: 'Tecnologia', ratio: 14 },

  // ═══ FINANZAS ═══
  { ticker: 'JPM.BA', name: 'JPMorgan Chase', localTicker: 'JPM', sector: 'Finanzas', ratio: 15 },
  { ticker: 'GS.BA', name: 'Goldman Sachs', localTicker: 'GS', sector: 'Finanzas', ratio: 13 },
  { ticker: 'BAC.BA', name: 'Bank of America', localTicker: 'BAC', sector: 'Finanzas', ratio: 4 },
  { ticker: 'C.BA', name: 'Citigroup Inc.', localTicker: 'C', sector: 'Finanzas', ratio: 3 },
  { ticker: 'WFC.BA', name: 'Wells Fargo', localTicker: 'WFC', sector: 'Finanzas', ratio: 5 },
  { ticker: 'V.BA', name: 'Visa Inc.', localTicker: 'V', sector: 'Finanzas', ratio: 18 },
  { ticker: 'MA.BA', name: 'Mastercard Inc.', localTicker: 'MA', sector: 'Finanzas', ratio: 33 },
  { ticker: 'AXP.BA', name: 'American Express', localTicker: 'AXP', sector: 'Finanzas', ratio: 15 },
  { ticker: 'SCHW.BA', name: 'Charles Schwab', localTicker: 'SCHW', sector: 'Finanzas', ratio: 13 },
  { ticker: 'BK.BA', name: 'Bank of New York Mellon', localTicker: 'BK', sector: 'Finanzas', ratio: 2 },
  { ticker: 'SPGI.BA', name: 'S&P Global', localTicker: 'SPGI', sector: 'Finanzas', ratio: 45 },
  { ticker: 'BX.BA', name: 'Blackstone Inc.', localTicker: 'BX', sector: 'Finanzas', ratio: 30 },
  { ticker: 'HOOD.BA', name: 'Robinhood Markets', localTicker: 'HOOD', sector: 'Fintech', ratio: 29 },
  { ticker: 'COIN.BA', name: 'Coinbase Global', localTicker: 'COIN', sector: 'Crypto', ratio: 27 },
  { ticker: 'HSBC.BA', name: 'HSBC Holdings', localTicker: 'HSBC', sector: 'Finanzas', ratio: 2 },
  { ticker: 'BBD.BA', name: 'Banco Bradesco', localTicker: 'BBD', sector: 'Finanzas', ratio: 1 },
  { ticker: 'ITUB.BA', name: 'Itau Unibanco', localTicker: 'ITUB', sector: 'Finanzas', ratio: 1 },
  { ticker: 'NU.BA', name: 'NU Holdings', localTicker: 'NU', sector: 'Fintech', ratio: 2 },
  { ticker: 'PAGS.BA', name: 'PagSeguro Digital', localTicker: 'PAGS', sector: 'Fintech', ratio: 3 },
  { ticker: 'XP.BA', name: 'XP Inc.', localTicker: 'XP', sector: 'Fintech', ratio: 4 },
  { ticker: 'HDB.BA', name: 'HDFC Bank', localTicker: 'HDB', sector: 'Finanzas', ratio: 2 },

  // ═══ FINANZAS ARGENTINA ═══
  { ticker: 'GGAL.BA', name: 'Grupo Financiero Galicia', localTicker: 'GGAL', sector: 'Finanzas ARG', ratio: 10 },
  { ticker: 'BBAR.BA', name: 'Banco BBVA Argentina', localTicker: 'BBAR', sector: 'Finanzas ARG', ratio: 3 },

  // ═══ SALUD ═══
  { ticker: 'JNJ.BA', name: 'Johnson & Johnson', localTicker: 'JNJ', sector: 'Salud', ratio: 15 },
  { ticker: 'PFE.BA', name: 'Pfizer Inc.', localTicker: 'PFE', sector: 'Salud', ratio: 4 },
  { ticker: 'MRK.BA', name: 'Merck & Co.', localTicker: 'MRK', sector: 'Salud', ratio: 5 },
  { ticker: 'ABBV.BA', name: 'AbbVie Inc.', localTicker: 'ABBV', sector: 'Salud', ratio: 10 },
  { ticker: 'ABT.BA', name: 'Abbott Laboratories', localTicker: 'ABT', sector: 'Salud', ratio: 4 },
  { ticker: 'LLY.BA', name: 'Eli Lilly', localTicker: 'LLY', sector: 'Salud', ratio: 56 },
  { ticker: 'BMY.BA', name: 'Bristol-Myers Squibb', localTicker: 'BMY', sector: 'Salud', ratio: 3 },
  { ticker: 'AMGN.BA', name: 'Amgen Inc.', localTicker: 'AMGN', sector: 'Salud', ratio: 30 },
  { ticker: 'GILD.BA', name: 'Gilead Sciences', localTicker: 'GILD', sector: 'Salud', ratio: 4 },
  { ticker: 'MRNA.BA', name: 'Moderna Inc.', localTicker: 'MRNA', sector: 'Salud', ratio: 19 },
  { ticker: 'VRTX.BA', name: 'Vertex Pharma', localTicker: 'VRTX', sector: 'Salud', ratio: 101 },
  { ticker: 'TMO.BA', name: 'Thermo Fisher', localTicker: 'TMO', sector: 'Salud', ratio: 22 },
  { ticker: 'UNH.BA', name: 'UnitedHealth Group', localTicker: 'UNH', sector: 'Salud', ratio: 33 },
  { ticker: 'NVS.BA', name: 'Novartis AG', localTicker: 'NVS', sector: 'Salud', ratio: 4 },
  { ticker: 'AZN.BA', name: 'AstraZeneca Plc', localTicker: 'AZN', sector: 'Salud', ratio: 2 },
  { ticker: 'CVS.BA', name: 'CVS Health', localTicker: 'CVS', sector: 'Salud', ratio: 15 },
  { ticker: 'MDT.BA', name: 'Medtronic Plc', localTicker: 'MDT', sector: 'Salud', ratio: 4 },

  // ═══ ENERGIA ═══
  { ticker: 'XOM.BA', name: 'Exxon Mobil', localTicker: 'XOM', sector: 'Energia', ratio: 10 },
  { ticker: 'CVX.BA', name: 'Chevron Corp.', localTicker: 'CVX', sector: 'Energia', ratio: 16 },
  { ticker: 'SHEL.BA', name: 'Shell Plc', localTicker: 'SHEL', sector: 'Energia', ratio: 2 },
  { ticker: 'BP.BA', name: 'BP Plc', localTicker: 'BP', sector: 'Energia', ratio: 5 },
  { ticker: 'TTE.BA', name: 'TotalEnergies', localTicker: 'TTE', sector: 'Energia', ratio: 3 },
  { ticker: 'OXY.BA', name: 'Occidental Petroleum', localTicker: 'OXY', sector: 'Energia', ratio: 5 },
  { ticker: 'SLB.BA', name: 'Schlumberger', localTicker: 'SLB', sector: 'Energia', ratio: 3 },
  { ticker: 'HAL.BA', name: 'Halliburton Co.', localTicker: 'HAL', sector: 'Energia', ratio: 2 },
  { ticker: 'PBR.BA', name: 'Petrobras', localTicker: 'PBR', sector: 'Energia', ratio: 1 },
  { ticker: 'FSLR.BA', name: 'First Solar', localTicker: 'FSLR', sector: 'Energia', ratio: 18 },
  { ticker: 'CEG.BA', name: 'Constellation Energy', localTicker: 'CEG', sector: 'Energia', ratio: 45 },
  { ticker: 'VST.BA', name: 'Vistra Corp.', localTicker: 'VST', sector: 'Energia', ratio: 26 },

  // ═══ ENERGIA ARGENTINA ═══
  { ticker: 'YPF.BA', name: 'YPF S.A.', localTicker: 'YPF', sector: 'Energia ARG', ratio: 1 },
  { ticker: 'PAM.BA', name: 'Pampa Energia', localTicker: 'PAM', sector: 'Energia ARG', ratio: 5 },
  { ticker: 'TGS.BA', name: 'Transp. Gas del Sur', localTicker: 'TGS', sector: 'Energia ARG', ratio: 5 },
  { ticker: 'VIST.BA', name: 'Vista Energy', localTicker: 'VIST', sector: 'Energia ARG', ratio: 3 },

  // ═══ CONSUMO DISCRECIONAL ═══
  { ticker: 'TSLA.BA', name: 'Tesla Inc.', localTicker: 'TSLA', sector: 'Automotriz', ratio: 15 },
  { ticker: 'DIS.BA', name: 'Walt Disney Co.', localTicker: 'DIS', sector: 'Entretenimiento', ratio: 12 },
  { ticker: 'NKE.BA', name: 'Nike Inc.', localTicker: 'NKE', sector: 'Consumo', ratio: 12 },
  { ticker: 'SBUX.BA', name: 'Starbucks Corp.', localTicker: 'SBUX', sector: 'Consumo', ratio: 12 },
  { ticker: 'MCD.BA', name: "McDonald's Corp.", localTicker: 'MCD', sector: 'Consumo', ratio: 24 },
  { ticker: 'HD.BA', name: 'Home Depot', localTicker: 'HD', sector: 'Consumo', ratio: 32 },
  { ticker: 'COST.BA', name: 'Costco Wholesale', localTicker: 'COST', sector: 'Consumo', ratio: 48 },
  { ticker: 'TGT.BA', name: 'Target Corp.', localTicker: 'TGT', sector: 'Consumo', ratio: 24 },
  { ticker: 'BKNG.BA', name: 'Booking Holdings', localTicker: 'BKNG', sector: 'Turismo', ratio: 700 },
  { ticker: 'GM.BA', name: 'General Motors', localTicker: 'GM', sector: 'Automotriz', ratio: 6 },
  { ticker: 'F.BA', name: 'Ford Motor Co.', localTicker: 'F', sector: 'Automotriz', ratio: 1 },
  { ticker: 'RACE.BA', name: 'Ferrari NV', localTicker: 'RACE', sector: 'Automotriz', ratio: 83 },
  { ticker: 'TM.BA', name: 'Toyota Motor', localTicker: 'TM', sector: 'Automotriz', ratio: 15 },
  { ticker: 'CCL.BA', name: 'Carnival Corp.', localTicker: 'CCL', sector: 'Turismo', ratio: 3 },
  { ticker: 'WMT.BA', name: 'Walmart Inc.', localTicker: 'WMT', sector: 'Consumo', ratio: 18 },
  { ticker: 'ARCO.BA', name: 'Arcos Dorados', localTicker: 'ARCO', sector: 'Consumo', ratio: 1 },

  // ═══ CONSUMO BASICO ═══
  { ticker: 'KO.BA', name: 'Coca-Cola Co.', localTicker: 'KO', sector: 'Consumo', ratio: 5 },
  { ticker: 'PEP.BA', name: 'PepsiCo Inc.', localTicker: 'PEP', sector: 'Consumo', ratio: 18 },
  { ticker: 'PG.BA', name: 'Procter & Gamble', localTicker: 'PG', sector: 'Consumo', ratio: 15 },
  { ticker: 'CL.BA', name: 'Colgate Palmolive', localTicker: 'CL', sector: 'Consumo', ratio: 3 },
  { ticker: 'PM.BA', name: 'Philip Morris Intl', localTicker: 'PM', sector: 'Consumo', ratio: 18 },
  { ticker: 'MO.BA', name: 'Altria Group', localTicker: 'MO', sector: 'Consumo', ratio: 4 },
  { ticker: 'UL.BA', name: 'Unilever Plc', localTicker: 'UL', sector: 'Consumo', ratio: 3 },
  { ticker: 'MDLZ.BA', name: 'Mondelez Intl', localTicker: 'MDLZ', sector: 'Consumo', ratio: 15 },
  { ticker: 'ABEV.BA', name: 'Ambev S.A.', localTicker: 'ABEV', sector: 'Consumo', ratio: 1 },

  // ═══ INDUSTRIAL ═══
  { ticker: 'CAT.BA', name: 'Caterpillar Inc.', localTicker: 'CAT', sector: 'Industrial', ratio: 20 },
  { ticker: 'DE.BA', name: 'Deere & Company', localTicker: 'DE', sector: 'Industrial', ratio: 40 },
  { ticker: 'HON.BA', name: 'Honeywell Intl', localTicker: 'HON', sector: 'Industrial', ratio: 8 },
  { ticker: 'BA.BA', name: 'Boeing Co.', localTicker: 'BA', sector: 'Industrial', ratio: 24 },
  { ticker: 'GE.BA', name: 'General Electric', localTicker: 'GE', sector: 'Industrial', ratio: 8 },
  { ticker: 'RTX.BA', name: 'Raytheon Technologies', localTicker: 'RTX', sector: 'Industrial', ratio: 5 },
  { ticker: 'MMM.BA', name: '3M Company', localTicker: 'MMM', sector: 'Industrial', ratio: 10 },
  { ticker: 'FDX.BA', name: 'FedEx Corp.', localTicker: 'FDX', sector: 'Industrial', ratio: 10 },
  { ticker: 'UNP.BA', name: 'Union Pacific', localTicker: 'UNP', sector: 'Industrial', ratio: 20 },
  { ticker: 'DAL.BA', name: 'Delta Air Lines', localTicker: 'DAL', sector: 'Aerolineas', ratio: 8 },
  { ticker: 'UAL.BA', name: 'United Airlines', localTicker: 'UAL', sector: 'Aerolineas', ratio: 5 },
  { ticker: 'AAL.BA', name: 'American Airlines', localTicker: 'AAL', sector: 'Aerolineas', ratio: 2 },
  { ticker: 'ADP.BA', name: 'Automatic Data Proc.', localTicker: 'ADP', sector: 'Industrial', ratio: 6 },
  { ticker: 'DD.BA', name: 'DuPont de Nemours', localTicker: 'DD', sector: 'Industrial', ratio: 5 },
  { ticker: 'DOW.BA', name: 'DOW Inc.', localTicker: 'DOW', sector: 'Industrial', ratio: 6 },
  { ticker: 'X.BA', name: 'United States Steel', localTicker: 'X', sector: 'Industrial', ratio: 3 },
  { ticker: 'ERJ.BA', name: 'Embraer S.A.', localTicker: 'ERJ', sector: 'Industrial', ratio: 1 },
  { ticker: 'CAAP.BA', name: 'Corp. America Airports', localTicker: 'CAAP', sector: 'Industrial', ratio: 1 },

  // ═══ MATERIALES / MINERIA ═══
  { ticker: 'GOLD.BA', name: 'Barrick Gold', localTicker: 'GOLD', sector: 'Mineria', ratio: 2 },
  { ticker: 'NEM.BA', name: 'Newmont Corp.', localTicker: 'NEM', sector: 'Mineria', ratio: 3 },
  { ticker: 'AEM.BA', name: 'Agnico Eagle Mines', localTicker: 'AEM', sector: 'Mineria', ratio: 6 },
  { ticker: 'KGC.BA', name: 'Kinross Gold', localTicker: 'KGC', sector: 'Mineria', ratio: 1 },
  { ticker: 'PAAS.BA', name: 'Pan American Silver', localTicker: 'PAAS', sector: 'Mineria', ratio: 3 },
  { ticker: 'HL.BA', name: 'Hecla Mining', localTicker: 'HL', sector: 'Mineria', ratio: 1 },
  { ticker: 'BHP.BA', name: 'BHP Group', localTicker: 'BHP', sector: 'Mineria', ratio: 2 },
  { ticker: 'RIO.BA', name: 'Rio Tinto', localTicker: 'RIO', sector: 'Mineria', ratio: 8 },
  { ticker: 'SCCO.BA', name: 'Southern Copper', localTicker: 'SCCO', sector: 'Mineria', ratio: 2 },
  { ticker: 'VALE.BA', name: 'Vale S.A.', localTicker: 'VALE', sector: 'Mineria', ratio: 2 },
  { ticker: 'NUE.BA', name: 'Nucor Corp.', localTicker: 'NUE', sector: 'Mineria', ratio: 16 },
  { ticker: 'MOS.BA', name: 'The Mosaic Co.', localTicker: 'MOS', sector: 'Materiales', ratio: 5 },
  { ticker: 'CX.BA', name: 'Cemex S.A.B.', localTicker: 'CX', sector: 'Materiales', ratio: 1 },

  // ═══ TELECOM ═══
  { ticker: 'T.BA', name: 'AT&T Inc.', localTicker: 'T', sector: 'Telecom', ratio: 3 },
  { ticker: 'VZ.BA', name: 'Verizon Communications', localTicker: 'VZ', sector: 'Telecom', ratio: 4 },
  { ticker: 'TMUS.BA', name: 'T-Mobile US', localTicker: 'TMUS', sector: 'Telecom', ratio: 33 },
  { ticker: 'AMX.BA', name: 'America Movil', localTicker: 'AMX', sector: 'Telecom', ratio: 1 },

  // ═══ CRYPTO / BLOCKCHAIN ═══
  { ticker: 'RIOT.BA', name: 'Riot Platforms', localTicker: 'RIOT', sector: 'Crypto', ratio: 3 },

  // ═══ AEROSPACE / SPACE ═══
  { ticker: 'RKLB.BA', name: 'Rocket Lab', localTicker: 'RKLB', sector: 'Aeroespacial', ratio: 12 },

  // ═══ ETFs ═══
  { ticker: 'SPY.BA', name: 'SPDR S&P 500 ETF', localTicker: 'SPY', sector: 'ETF', ratio: 20 },
  { ticker: 'QQQ.BA', name: 'Invesco QQQ (Nasdaq 100)', localTicker: 'QQQ', sector: 'ETF', ratio: 20 },
  { ticker: 'DIA.BA', name: 'SPDR Dow Jones ETF', localTicker: 'DIA', sector: 'ETF', ratio: 20 },
  { ticker: 'IWM.BA', name: 'iShares Russell 2000', localTicker: 'IWM', sector: 'ETF', ratio: 10 },
  { ticker: 'EEM.BA', name: 'iShares Emerging Markets', localTicker: 'EEM', sector: 'ETF', ratio: 2 },
  { ticker: 'EWZ.BA', name: 'iShares MSCI Brazil', localTicker: 'EWZ', sector: 'ETF', ratio: 2 },
  { ticker: 'ARKK.BA', name: 'ARK Innovation ETF', localTicker: 'ARKK', sector: 'ETF', ratio: 10 },
  { ticker: 'XLE.BA', name: 'Energy Select SPDR', localTicker: 'XLE', sector: 'ETF', ratio: 2 },
  { ticker: 'XLF.BA', name: 'Financial Select SPDR', localTicker: 'XLF', sector: 'ETF', ratio: 2 },
  { ticker: 'XLK.BA', name: 'Technology Select SPDR', localTicker: 'XLK', sector: 'ETF', ratio: 46 },
  { ticker: 'XLV.BA', name: 'Health Care Select SPDR', localTicker: 'XLV', sector: 'ETF', ratio: 29 },
  { ticker: 'IBIT.BA', name: 'iShares Bitcoin Trust', localTicker: 'IBIT', sector: 'ETF', ratio: 10 },
  { ticker: 'GLD.BA', name: 'SPDR Gold Trust', localTicker: 'GLD', sector: 'ETF', ratio: 50 },
  { ticker: 'SLV.BA', name: 'iShares Silver Trust', localTicker: 'SLV', sector: 'ETF', ratio: 6 },
  { ticker: 'GDX.BA', name: 'VanEck Gold Miners', localTicker: 'GDX', sector: 'ETF', ratio: 10 },
  { ticker: 'IBB.BA', name: 'iShares Biotech ETF', localTicker: 'IBB', sector: 'ETF', ratio: 27 },
  { ticker: 'FXI.BA', name: 'iShares China Large-Cap', localTicker: 'FXI', sector: 'ETF', ratio: 5 },
  { ticker: 'EFA.BA', name: 'iShares MSCI EAFE', localTicker: 'EFA', sector: 'ETF', ratio: 18 },
  { ticker: 'USO.BA', name: 'United States Oil Fund', localTicker: 'USO', sector: 'ETF', ratio: 15 },
  { ticker: 'ACWI.BA', name: 'iShares MSCI ACWI', localTicker: 'ACWI', sector: 'ETF', ratio: 26 },
  { ticker: 'ILF.BA', name: 'iShares Latin America 40', localTicker: 'ILF', sector: 'ETF', ratio: 6 },
  { ticker: 'COPX.BA', name: 'Global X Copper Miners', localTicker: 'COPX', sector: 'ETF', ratio: 14 },
  { ticker: 'TQQQ.BA', name: 'ProShares UltraPro QQQ', localTicker: 'TQQQ', sector: 'ETF', ratio: 25 },
];

export function findCedear(ticker: string): CedearInfo | undefined {
  const normalized = ticker.toUpperCase();
  return CEDEAR_LIST.find(
    (c) => c.ticker === normalized || c.localTicker === normalized
  );
}
